# -*- coding: utf-8 -*-
"""Testing in cv 2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cIeBYjk1ceW3B1GPVy4oDLpk1-75Xt5Z
"""

# ── Step 1: Install ──
!pip install groq -q

# ── Step 2: Set API key from Colab secrets ──
from google.colab import userdata
import os
os.environ["API_KEY"] = userdata.get("GROQ_KEY")

# ── Step 3: Upload these two files to Colab ──
# evaluate_reginsaaf.py
# reg_test_memberN.csv   ← your assigned slice

# ── Step 4: Test the parser first ──
!python evaluate_reginsaaf.py --test
# Should print: 11/11 passed



# ── Step 5: Run 70B evaluation ──
!python evaluate_reginsaaf.py \
  --dataset reg_test_member1.csv \
  --backend groq \
  --model llama-3.3-70b-versatile \
  --out memberN_70b

# ── Step 6: Download your result ──
from google.colab import files
files.download("member1_70b_results.json")

from google.colab import files
files.download("memberN_70b_results.json")

# ── Step 5: Run 70B evaluation ──
!python evaluate_reginsaaf.py \
  --dataset reg_test_member2.csv \
  --backend groq \
  --model llama-3.3-70b-versatile \
  --out member2_70b

# ── Step 6: Download your result ──
from google.colab import files
files.download("member2_70b_results.json")

# ── Step 5: Run 70B evaluation ──
!python evaluate_reginsaaf.py \
  --dataset reg_test_member3.csv \
  --backend groq \
  --model llama-3.3-70b-versatile \
  --out member3_70b

# ── Step 6: Download your result ──
from google.colab import files
files.download("member3_70b_results.json")
files.download("member3_70b_report.json")

# ── Step 5: Run 70B evaluation ──
!python evaluate_reginsaaf.py \
  --dataset reg_test_member4.csv \
  --backend groq \
  --model llama-3.3-70b-versatile \
  --out member4_70b

# ── Step 6: Download your result ──
from google.colab import files
files.download("member4_70b_results.json")
files.download("member4_70b_report.json")

# ── Step 5: Run 70B evaluation ──
!python evaluate_reginsaaf.py \
  --dataset reg_test_member5.csv \
  --backend groq \
  --model llama-3.3-70b-versatile \
  --out member5_70b

# ── Step 6: Download your result ──
from google.colab import files
files.download("member5_70b_results.json")
files.download("member5_70b_report.json")

exec(open("colab_merge_70b.py").read())

import json

results = json.load(open("merged_70b_results.json"))
abstains = [r for r in results if r["predicted"] == "Abstain"]

print(f"Total abstains: {len(abstains)}")
print()

# Show 5 raw responses
for r in abstains[:5]:
    print(f"ID: {r['id']} | axis={r['axis']} cond={r['condition']} law={r['law']}")
    print(f"RAW (last 300 chars):")
    print(repr(r["raw_response"][-300:]))
    print("---")

import json, csv, time, os
from groq import Groq

# ── config ──
API_KEY    = os.environ.get("API_KEY")
MODEL      = "llama-3.3-70b-versatile"
MAX_TOKENS = 1500
SLEEP_BASE = 60   # seconds to wait on 429

client = Groq(api_key=API_KEY)

# ── load merged results ──
results = json.load(open("merged_70b_results.json"))
to_rerun = [r for r in results if r["raw_response"] == ""]
print(f"Entries to rerun: {len(to_rerun)}")

# ── parser (same as evaluate_reginsaaf.py) ──
import re

def parse_response(raw):
    if not raw:
        return "Abstain"
    text = raw.strip()
    lo   = text.lower()
    lines = [l.strip() for l in text.splitlines() if l.strip()]
    if lines:
        last = lines[-1].lower().strip(".' \"")
        if last in ("yes", "yes."): return "Yes"
        if last in ("no",  "no."):  return "No"
    m = re.search(r"is:\s*(yes|no)\b", lo)
    if m: return "Yes" if m.group(1) == "yes" else "No"
    for marker in ["final answer:", "answer:", "therefore the answer is",
                   "my answer is", "conclusion:", "determination:",
                   "the answer is", "in conclusion"]:
        m = re.search(re.escape(marker) + r"\s*(yes|no)\b", lo)
        if m: return "Yes" if m.group(1) == "yes" else "No"
    sentences = re.split(r"[.!?]", lo)
    for sent in reversed(sentences):
        sent = sent.strip()
        if re.fullmatch(r"(yes|no)", sent): return "Yes" if sent=="yes" else "No"
        if "the law is not applicable" in sent: return "No"
        if "not applicable" in sent:            return "No"
        if "the law is applicable" in sent:     return "Yes"
        if "is applicable" in sent:             return "Yes"
    yes_n = len(re.findall(r"(?<!not )(?<!never )\byes\b", lo))
    no_n  = len(re.findall(r"\bno\b", lo))
    na_n  = len(re.findall(r"not applicable", lo))
    ap_n  = len(re.findall(r"(?<!not )(?<!never )is applicable", lo))
    score = (yes_n + ap_n) - (no_n + na_n)
    if score > 0: return "Yes"
    if score < 0: return "No"
    return "Abstain"

def build_prompt(entry):
    suffix = "\n\nAfter your step-by-step reasoning above, your final one-word answer is:"
    return "{}\n\n{}{}".format(entry["instruction"], entry["input"], suffix)

# ── rerun with retry ──
id_map = {r["id"]: r for r in results}

for i, r in enumerate(to_rerun):
    print(f"[{i+1}/{len(to_rerun)}] {r['id']} axis={r['axis']} cond={r['condition']}")
    prompt = build_prompt(r)
    raw    = ""

    for attempt in range(5):
        try:
            resp = client.chat.completions.create(
                model=MODEL,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.0,
                max_tokens=MAX_TOKENS,
            )
            raw = resp.choices[0].message.content.strip()
            break
        except Exception as e:
            msg = str(e)
            if "429" in msg:
                wait = SLEEP_BASE * (attempt + 1)
                print(f"  Rate limit — waiting {wait}s (attempt {attempt+1}/5)")
                time.sleep(wait)
            else:
                print(f"  Error: {msg}")
                break

    predicted = parse_response(raw)

    # Update in-place
    id_map[r["id"]]["raw_response"] = raw
    id_map[r["id"]]["predicted"]    = predicted
    id_map[r["id"]]["correct"]      = predicted == r["ground_truth"]

    if (i+1) % 10 == 0:
        # Checkpoint save every 10 entries
        with open("merged_70b_results_fixed.json", "w") as f:
            json.dump(results, f, indent=2, ensure_ascii=False)
        remaining_empty = sum(1 for x in results if x["raw_response"] == "")
        print(f"  Checkpoint saved. Still empty: {remaining_empty}")

# ── final save ──
with open("merged_70b_results_fixed.json", "w", encoding="utf-8") as f:
    json.dump(results, f, indent=2, ensure_ascii=False)

still_empty = sum(1 for r in results if r["raw_response"] == "")
print(f"\nDone. Still empty: {still_empty}/{len(results)}")
print("Saved: merged_70b_results_fixed.json")

# Upload these files:
# - colab_rerun_final.py
# - merged_70b_results.json
# - reg_test_member1.csv through member5.csv

# Set your key
from google.colab import userdata
import os
os.environ["API_KEY"] = userdata.get("GROQ_KEY1")

# Run
exec(open("colab_rerun_final.py").read())

!pip install groq -q

# ── Step 2: Set API key from Colab secrets ──
from google.colab import userdata
import os
os.environ["API_KEY"] = userdata.get("llmnew")

!python evaluate_reginsaaf.py --test

"""**Using 120B LLM open ai model for testing**"""

# ── Step 5: Run 120B evaluation ──
!python evaluate_reginsaaf.py \
  --dataset reg_test_member3.csv \
  --backend groq \
  --model openai/gpt-oss-120b \
  --out member3_120b

# ── Step 6: Download your result ──
from google.colab import files
files.download("member3_120b_results.json")
files.download("member3_120b_report.json")

"""**8B evaluation on 100 entries**"""

# ── Step 5: Run 8B evaluation ──
!python evaluate_reginsaaf.py \
  --dataset reg_test_member3.csv \
  --backend groq \
  --model llama-3.1-8b-instant \
  --out member3_8b

# ── Step 6: Download your result ──
from google.colab import files
files.download("member3_8b_results.json")
files.download("member3_8b_report.json")

"""**8B testing on 500 entries**"""

# ── Step 5: Run 8B evaluation ──
!python evaluate_reginsaaf.py \
  --dataset reg_test_withid.csv \
  --backend groq \
  --model llama-3.1-8b-instant \
  --out member3_8b

# ── Step 6: Download your result ──
from google.colab import files
files.download("reg_test_withid_results.json")
files.download("reg_test_wihtid_report.json")