# -*- coding: utf-8 -*-
"""testing part 4 Minakshi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sSMZrvBj_24aPTWl1Gv07uB7FQQI6QpJ
"""

# ── Step 1: Install ──
!pip install groq -q

# ── Step 2: Set API key from Colab secrets ──
from google.colab import userdata
import os
os.environ["API_KEY"] = userdata.get("GROQ_KEY")

# ── Step 3: Upload these two files to Colab ──
# evaluate_reginsaaf.py
# reg_test_memberN.csv   ← your assigned slice

# ── Step 4: Test the parser first ──
!python evaluate_reginsaaf.py --test
# Should print: 11/11 passed

import pandas as pd

df = pd.read_csv("dataset_part_4_minakshi.csv")
print(df.columns)

import pandas as pd

df = pd.read_csv("dataset_part_4_minakshi.csv")

# lowercase all columns
df.columns = df.columns.str.lower()

# fix all mismatches
df = df.rename(columns={
    "prompt": "instruction",
    "prompt_wo_reg_id": "input",
    "correct_output": "output",
    "cf_pair_id": "counterfactual_pair_id"
})

df.to_csv("dataset_fixed.csv", index=False)

print("Now EVERYTHING is aligned")
print(df.columns)

!python evaluate_reginsaaf.py \
  --dataset dataset_fixed.csv \
  --backend groq \
  --model llama3-8b-8192 \
  --out member4_8b

# ── Step 6: Download your result ──
from google.colab import files
files.download("member4_8b_results.json")
files.download("member4_8b_report.json")