# -*- coding: utf-8 -*-
"""testing part 4 Minakshi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sSMZrvBj_24aPTWl1Gv07uB7FQQI6QpJ
"""

# ── Step 1: Install ──
!pip install groq -q

# ── Step 2: Set API key from Colab secrets ──
from google.colab import userdata
import os
os.environ["API_KEY"] = userdata.get("GROQ_KEY")

# ── Step 3: Upload these two files to Colab ──
# evaluate_reginsaaf.py
# reg_test_memberN.csv   ← your assigned slice

# ── Step 4: Test the parser first ──
!python evaluate_reginsaaf.py --test
# Should print: 11/11 passed

import pandas as pd

df = pd.read_csv("dataset_part_4_minakshi.csv")
print(df.columns)

import pandas as pd

df = pd.read_csv("dataset_part_4_minakshi.csv")

# lowercase all columns
df.columns = df.columns.str.lower()

# fix all mismatches
df = df.rename(columns={
    "prompt": "instruction",
    "prompt_wo_reg_id": "input",
    "correct_output": "output",
    "cf_pair_id": "counterfactual_pair_id"
})

df.to_csv("dataset_fixed.csv", index=False)

print("Now EVERYTHING is aligned")
print(df.columns)

!python evaluate_reginsaaf.py \
  --dataset dataset_fixed.csv \
  --backend groq \
  --model llama3-8b-8192 \
  --out member4_8b

# ── Step 6: Download your result ──
from google.colab import files
files.download("member4_8b_results.json")
files.download("member4_8b_report.json")

# ── Step 5: Run 70B evaluation ──
!python evaluate_reginsaaf.py \
  --dataset dataset_fixed.csv \
  --backend groq \
  --model llama-3.3-70b-versatile \
  --out member4_70b

# ── Step 6: Download your result ──
from google.colab import files
files.download("member4_70b_results.json")
files.download("member4_70b_report.json")

# Step 7: Model Evaluation and Performance Comparison
import pandas as pd

df8 = pd.read_csv("member4_8b_results.csv")
df70 = pd.read_csv("member4_70b_results.csv")

df = df8.merge(df70, on="id", suffixes=("_8b", "_70b"))

# Compare outputs
df["same_output"] = df["predicted_8b"] == df["predicted_70b"]

# Accuracy (use either _8b or _70b ground truth, both same)
acc_8b = (df["predicted_8b"] == df["ground_truth_8b"]).mean()
acc_70b = (df["predicted_70b"] == df["ground_truth_70b"]).mean()

print("8B Accuracy:", acc_8b)
print("70B Accuracy:", acc_70b)

# Optional: agreement %
agreement = df["same_output"].mean()
print("Model Agreement:", agreement)

